package pl.zimowski.moo.api;

/**
 * Handling of actions generated by a client. Typically implemented by specific client
 * library (eg; web socket client, jms client, etc). UI that depends on a client will
 * almost always inject by interface expecting the client to provide the one and only
 * available implementation. As UI is not bound to any particular client, it must not
 * and it should not care about the implementation.
 *
 * @since 1.2.0
 * @author Adam Zimowski (<a href="mailto:mrazjava@yandex.com">mrazjava</a>)
 */
public interface ClientHandling {

	/**
	 * Establises connection with the server. This call is generally required before
	 * events can be sent.
	 *
	 * @param reporter (provided by the UI) where events should be reported to
	 * @return {@code true} if connection was successfully established; {@code false} otherwise
	 */
	boolean connect(ClientReporting reporter);

	/**
	 * Determines if connection between a client and a server is established.
	 *
	 * @return {@code true} if client is connected to a server; {@code false} otherwise
	 */
	boolean isConnected();

	/**
	 * Terminates server connection. After this call, subsequent sending of events
	 * will fail.
	 */
	void disconnect();

	/**
	 * Notifies the server of a specific event on a client side. The server will generally
	 * respond with either a public or a private message. A public message is one that will
	 * be broadcasted to all the clients, and private one will be the one that will be sent
	 * to the client that caused the server event.
	 *
	 * @param event to be sent to the server
	 */
	void send(ClientEvent event);
}
