language:
 - java
dist:
 - trusty
jdk:
 - openjdk11
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify jacoco:report
after_success:
  - mvn coveralls:report