package pl.zimowski.moo.ui.shell.reader;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import pl.zimowski.moo.api.ClientHandling;
import pl.zimowski.moo.api.ClientListener;
import pl.zimowski.moo.api.ServerAction;
import pl.zimowski.moo.api.ServerEvent;

/**
 * Reports chat events to the UI console.
 * 
 * @since 1.2.0
 * @author Adam Zimowski (<a href="mailto:mrazjava@yandex.com">mrazjava</a>)
 */
@Component
public class EventReporter implements ClientListener {

	static final Logger LOG = LoggerFactory.getLogger("CHAT_ECHO");
	
	private static final Logger log = LoggerFactory.getLogger(EventReporter.class);
	
	/**
	 * Name reported as author of messages generated by the UI reader.
	 */
	static final String AUTHOR = "reader";
	
	private String nick;
	
	@Inject
	private ClientHandling clientHandler;
	
	private String clientId;
	
	
	@Override
	public void onEvent(ServerEvent event) {

		log.debug(event.toString());
		
		String author = event.getAuthor();
		
        if(event.getAction() == ServerAction.ConnectionEstablished) {
        	clientId = event.getClientId();
        	LOG.info("({}): connected, client id: {}", author, clientId);
        }
        else if(event.getAction() == ServerAction.NickGenerated) {
            nick = event.getMessage();
            LOG.info("({}): You will be known as '{}'", author, nick);

        }
        else if(event.getAction() == ServerAction.ServerExit) {
        	LOG.info("({}) connection terminated by server; bye!", author);
        	clientHandler.disconnect();
        }
        else {
        	LOG.info("({}): {}", author, event.getMessage());
        }
	}
	
	@Override
	public void onBeforeServerConnect(String host, int port) {
		LOG.info("({}) establishing connection to {}:{}", AUTHOR, host, port);
	}

	@Override
	public void onConnectToServerError(String error) {
		LOG.info("(()) could not establish server connection: {}", AUTHOR, error);
	}

	String getClientId() {
		return clientId;
	}
	
	String getNick() {
		return nick;
	}
	
	void setNick(String nick) {
		this.nick = nick;
	}
}
