package pl.zimowski.moo.client.socket;

import javax.inject.Inject;

import org.springframework.stereotype.Component;

import pl.zimowski.moo.api.ClientEvent;
import pl.zimowski.moo.api.ClientHandling;
import pl.zimowski.moo.api.ClientReporting;

/**
 * Handles operations generated by the client. This implementation delegates
 * actual work to {@link ConnectionManagement}.
 *
 * @since 1.1.0
 * @author Adam Zimowski (<a href="mailto:mrazjava@yandex.com">mrazjava</a>)
 */
@Component
public class ClientHandler implements ClientHandling {

    @Inject
    private ConnectionManagement connectionManager;

    @Override
    public void send(ClientEvent event) {
        connectionManager.send(event);
    }

    @Override
    public boolean connect(ClientReporting reporter) {
        return connectionManager.connect(reporter);
    }

    @Override
    public boolean isConnected() {
        return connectionManager.isConnected();
    }

    @Override
    public void disconnect() {
        connectionManager.disconnect();
    }
}