package pl.zimowski.moo.server;

import pl.zimowski.moo.api.ServerEvent;

/**
 * Handler of a live connection between client and server. Listens for events
 * generated by a connected client and emits them onto a server. Likewise,
 * listens for events from the server and emits them back to a client.
 *
 * @since 1.0.0
 * @author Adam Zimowski (<a href="mailto:mrazjava@yandex.com">mrazjava</a>)
 */
public class ClientThread extends Thread implements ClientNotification {

    @Override
    public void notify(ServerEvent event) {
        // TODO Auto-generated method stub

    }
}